[package]
name = "bannify"
version = "0.1.0"
edition = "2021"
authors = ["Aaron Fulton"]

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.9"
glob = "0.3.2"
dirs = "6.0.0"
